/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hade-0.1.0.0 */
#ifndef VERSION_hade
#define VERSION_hade "0.1.0.0"
#endif /* VERSION_hade */
#ifndef MIN_VERSION_hade
#define MIN_VERSION_hade(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hade */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package base-4.15.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.15.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  15 || \
  (major1) == 4 && (major2) == 15 && (minor) <= 1)
#endif /* MIN_VERSION_base */
/* package base64-bytestring-1.2.1.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.2.1.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_base64_bytestring */
/* package binary-0.8.8.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.8.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 8)
#endif /* MIN_VERSION_binary */
/* package bytestring-0.10.12.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */
/* package bytestring-conversion-0.3.2 */
#ifndef VERSION_bytestring_conversion
#define VERSION_bytestring_conversion "0.3.2"
#endif /* VERSION_bytestring_conversion */
#ifndef MIN_VERSION_bytestring_conversion
#define MIN_VERSION_bytestring_conversion(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring_conversion */
/* package containers-0.6.4.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.4.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 4)
#endif /* MIN_VERSION_containers */
/* package csv-0.1.2 */
#ifndef VERSION_csv
#define VERSION_csv "0.1.2"
#endif /* VERSION_csv */
#ifndef MIN_VERSION_csv
#define MIN_VERSION_csv(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_csv */
/* package csv-conduit-0.7.3.0 */
#ifndef VERSION_csv_conduit
#define VERSION_csv_conduit "0.7.3.0"
#endif /* VERSION_csv_conduit */
#ifndef MIN_VERSION_csv_conduit
#define MIN_VERSION_csv_conduit(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 3)
#endif /* MIN_VERSION_csv_conduit */
/* package csv2json-0.1.0.0 */
#ifndef VERSION_csv2json
#define VERSION_csv2json "0.1.0.0"
#endif /* VERSION_csv2json */
#ifndef MIN_VERSION_csv2json
#define MIN_VERSION_csv2json(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_csv2json */
/* package distributed-process-0.7.4 */
#ifndef VERSION_distributed_process
#define VERSION_distributed_process "0.7.4"
#endif /* VERSION_distributed_process */
#ifndef MIN_VERSION_distributed_process
#define MIN_VERSION_distributed_process(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 4)
#endif /* MIN_VERSION_distributed_process */
/* package distributed-process-simplelocalnet-0.2.4 */
#ifndef VERSION_distributed_process_simplelocalnet
#define VERSION_distributed_process_simplelocalnet "0.2.4"
#endif /* VERSION_distributed_process_simplelocalnet */
#ifndef MIN_VERSION_distributed_process_simplelocalnet
#define MIN_VERSION_distributed_process_simplelocalnet(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_distributed_process_simplelocalnet */
/* package endo-0.3.0.1 */
#ifndef VERSION_endo
#define VERSION_endo "0.3.0.1"
#endif /* VERSION_endo */
#ifndef MIN_VERSION_endo
#define MIN_VERSION_endo(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_endo */
/* package hint-0.9.0.6 */
#ifndef VERSION_hint
#define VERSION_hint "0.9.0.6"
#endif /* VERSION_hint */
#ifndef MIN_VERSION_hint
#define MIN_VERSION_hint(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_hint */
/* package json-0.10 */
#ifndef VERSION_json
#define VERSION_json "0.10"
#endif /* VERSION_json */
#ifndef MIN_VERSION_json
#define MIN_VERSION_json(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_json */
/* package lens-5.0.1 */
#ifndef VERSION_lens
#define VERSION_lens "5.0.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_lens */
/* package lens-aeson-1.1.3 */
#ifndef VERSION_lens_aeson
#define VERSION_lens_aeson "1.1.3"
#endif /* VERSION_lens_aeson */
#ifndef MIN_VERSION_lens_aeson
#define MIN_VERSION_lens_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_lens_aeson */
/* package network-transport-0.5.4 */
#ifndef VERSION_network_transport
#define VERSION_network_transport "0.5.4"
#endif /* VERSION_network_transport */
#ifndef MIN_VERSION_network_transport
#define MIN_VERSION_network_transport(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_network_transport */
/* package network-transport-tcp-0.8.0 */
#ifndef VERSION_network_transport_tcp
#define VERSION_network_transport_tcp "0.8.0"
#endif /* VERSION_network_transport_tcp */
#ifndef MIN_VERSION_network_transport_tcp
#define MIN_VERSION_network_transport_tcp(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_network_transport_tcp */
/* package parsec-3.1.14.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.14.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 14)
#endif /* MIN_VERSION_parsec */
/* package servant-server-0.19.1 */
#ifndef VERSION_servant_server
#define VERSION_servant_server "0.19.1"
#endif /* VERSION_servant_server */
#ifndef MIN_VERSION_servant_server
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 1)
#endif /* MIN_VERSION_servant_server */
/* package stm-2.5.0.0 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.0.0"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_stm */
/* package template-0.2.0.10 */
#ifndef VERSION_template
#define VERSION_template "0.2.0.10"
#endif /* VERSION_template */
#ifndef MIN_VERSION_template
#define MIN_VERSION_template(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_template */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package th-abstraction-0.4.5.0 */
#ifndef VERSION_th_abstraction
#define VERSION_th_abstraction "0.4.5.0"
#endif /* VERSION_th_abstraction */
#ifndef MIN_VERSION_th_abstraction
#define MIN_VERSION_th_abstraction(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_VERSION_th_abstraction */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package unordered-containers-0.2.17.0 */
#ifndef VERSION_unordered_containers
#define VERSION_unordered_containers "0.2.17.0"
#endif /* VERSION_unordered_containers */
#ifndef MIN_VERSION_unordered_containers
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 17)
#endif /* MIN_VERSION_unordered_containers */
/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */
/* package vector-0.12.3.1 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.3.1"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_vector */
/* package warp-3.3.21 */
#ifndef VERSION_warp
#define VERSION_warp "3.3.21"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 21)
#endif /* MIN_VERSION_warp */
/* package word8-0.1.3 */
#ifndef VERSION_word8
#define VERSION_word8 "0.1.3"
#endif /* VERSION_word8 */
#ifndef MIN_VERSION_word8
#define MIN_VERSION_word8(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_word8 */
/* package xlsx-0.8.4 */
#ifndef VERSION_xlsx
#define VERSION_xlsx "0.8.4"
#endif /* VERSION_xlsx */
#ifndef MIN_VERSION_xlsx
#define MIN_VERSION_xlsx(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_VERSION_xlsx */
/* package xlsx-tabular-0.2.2.1 */
#ifndef VERSION_xlsx_tabular
#define VERSION_xlsx_tabular "0.2.2.1"
#endif /* VERSION_xlsx_tabular */
#ifndef MIN_VERSION_xlsx_tabular
#define MIN_VERSION_xlsx_tabular(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_xlsx_tabular */

/* tool gcc-9 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.0.2 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.0.2"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.0.2 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.0.2"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.25.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.25.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  25 || \
  (major1) == 2 && (major2) == 25 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.19.11 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.11"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 11)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.0.2 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.0.2"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.34 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.34"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  34 || \
  (major1) == 2 && (major2) == 34 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hade-0.1.0.0-8MxbsUpwRIJC1P7l9zc0R3-hade-client"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
